### ISSUE TITLE
Kaite Tasks

### ISSUE THREAD

**Issue by kconner3815** [kconner3815/test-project#4]
## Tasks:
- [ ] Research the Ticket Master API 
- [ ] Make a pull request to get all files 
- [ ] Set up HTML doc with form and buttons 
- [ ] Look into new libraries
- [ ] Write CSS / Create Responsive Design using bootstrap / foundation
